### ISSUE TITLE
Review and Edit Introduction

### ISSUE THREAD

**Issue by jrnold** [jrnold/qss-tidy#16]
Read and edit the introduction chapter. Fix any problems. Expand, revise, or edit the text for clarity. Ask questions in the comments of this issue or open a new issue if there are major changes that need to be made.

Note: when editing the text, keep to code. We can include comments to explain the code, or adds additional information to QSS, but we can't include so much that we are reproducing QSS.

**Comment by calvinhgarner** [comment]
In the note above, what do you mean by 'keep to code'?

**Comment by jrnold** [comment]
I meant that we have to mostly just include translations of the code blocks so as not to rewrite QSS.

**Comment by calvinhgarner** [comment]
1. It might be good to develop a standard text that you put in any sections of the book that do not have any relevant code to translate. The problem is that for sections 1.1 and 1.2 it looks like text is missing. Would you like me to do this?

2. For completeness, should the introduction include installing the qss package and loading it?

3. On line 196 you write 

> However, note that, by default, `[` will return a vector rather than a data frame if only one column is selected. 

But the first example in the code chunk above shows that using `[` seems to return a tibble. Am I confused here? I thought a tibble by definition could not be a vector.

4.  Is the following correct about group_by? You didn't name the function, but I think this is what you meant.
> The function `n()` when used in a **dplyr** function returns the number of rows in the data frame (or the number of rows in the group if used with `group_by()`).

5. I don't know how you want to finish these sentences:

> This means that while you should not save the entire workplace it is perfectly fine practice to run a script and save or load R objects to files, using  or .

> One thing to note is that Stata and SPSS have different concept

6. I think you should develop a standard for how you want to refer to packages on first reference (maybe with the link?), second reference, etc. Currently it is not clear to me when you want to bold package names in text and when you want to supply external links.

7. I don't understand the placement of the word 'Colophon' in the introduction. Why is it there?

**Comment by jrnold** [comment]
> 1. It might be good to develop a standard text that you put in any sections of the book that do not have any relevant code to translate. The problem is that for sections 1.1 and 1.2 it looks like text is missing. Would you like me to do this?

Yes

> 2. For completeness, should the introduction include installing the qss package and loading it?

Yes

> 3. On line 196 you write 

> > However, note that, by default, `[` will return a vector rather than a data frame if only one column is selected. 

> But the first example in the code chunk above shows that using `[` seems to return a tibble. Am I confused here? I thought a tibble by definition could not be a vector.

I'll change this. One of the primary differences between `tibbles` and `data.frame` objects is when they drop dimensions. With a `data.frame` or `matrix` object, if `[` returns a single column, it will coerce the returned object to a vector unless `drop=FALSE`. With `tibble` objects, it never drops dimensions and always returns `tibble` objects, making code more predictable.

> 4.  Is the following correct about group_by? You didn't name the function, but I think this is what you meant.
> > The function `n()` when used in a **dplyr** function returns the number of rows in the data frame (or the number of rows in the group if used with `group_by()`).

Yes, that's correct. 

> 5. I don't know how you want to finish these sentences:

> > This means that while you should not save the entire workplace it is perfectly fine practice to run a script and save or load R objects to files, using  or .

> > One thing to note is that Stata and SPSS have different concept

I'll fix.

> 6. I think you should develop a standard for how you want to refer to packages on first reference >
(maybe with the link?), second reference, etc. Currently it is not clear to me when you want to bold package names in text and when you want to supply external links.

Yeah, I probably should, though I'm not sure it's worth the copy-editing effort. Perhaps replace the first instance of a package or function in a chapter with a link.

> 7. I don't understand the placement of the word 'Colophon' in the introduction. Why is it there? 

I'm following http://r4ds.had.co.nz/introduction.html

**Comment by jrnold** [comment]
@calvinhgarner  Make those other changes. Then close the issue.

**Comment by calvinhgarner** [comment]
This is done, but I have opened a new issue to streamline the treatment of packages throughout the book. I don't have time to come up with a good system for this right now, but will get back to it.
