### ISSUE TITLE
Review and Edit Causality Chapter

### ISSUE THREAD

**Issue by jrnold** [jrnold/qss-tidy#17]
Read and edit the introduction chapter. Fix any problems. Expand, revise, or edit the text for clarity. Ask questions in the comments of this issue or open a new issue if there are major changes that need to be made.

Note: when editing the text, keep to code. We can include comments to explain the code, or adds additional information to QSS, but we can't include so much that we are reproducing QSS.

**Comment by calvinhgarner** [comment]
1. I think that I need more information on what you are trying to accomplish with the if_else example. You provide the following code:

> resume %>%
  mutate(BlackFemale = if_else(race == "black" & sex == "female", 1, 0)) %>%
  group_by(BlackFemale, race, sex) %>%
  count()

But it is unclear to me how/why this is any better than simply:

> resume %>%
  group_by(race, sex) %>%
  count()

2. The following sentence needs to be finished. I assume you mean to say 'between numerics and integers' but I am not sure.

> because `1L` is an integer and `0` is numeric (a floating-point number)
The distinction between integers and numeric variables is often invisible because most functions coerce variables between 

3. Does the r code in the code chunks automatically generate the r output or do I need to copy and paste the output if I change the code?

4. The following code seems to be formatted very differently than previous examples in that it doesn't use the %>% operator, it selects columns with double brackets rather than tidyverse functions--any reason for this? Should it be made stylistically similar to other code chunks?

> (filter(full_prop_by_state, state == "NJ")[["fullPropAfter"]] -
  filter(full_prop_by_state, state == "PA")[["fullPropAfter"]])

5. These links seems to be broken: 

- <img src="causality_files/figure-html/unnamed-chunk-42-1.png" width="70%" style="display: block; margin: auto;" />

- <img src="causality_files/figure-html/unnamed-chunk-44-1.png" width="70%" style="display: block; margin: auto;" />

- <img src="causality_files/figure-html/unnamed-chunk-50-1.png" width="70%" style="display: block; margin: auto;" />

-

**Comment by jrnold** [comment]
> The following code seems to be formatted very differently than previous examples in that it doesn't use the %>% operator, it selects columns with double brackets rather than tidyverse functions--any reason for this? Should it be made stylistically similar to other code chunks?

Using `[[` is not non-tidyverse (using `subset`, `transform`, `aggregate` or `tapply` would be). In this case we need the value of `fullPropAfter`. Select would return a `tibble`.

**Comment by jrnold** [comment]
> Does the r code in the code chunks automatically generate the r output or do I need to copy and paste the output if I change the code?

Yes, the r code generates the output. This question was probably because you were editing the md file, and not the Rmd file.

**Comment by jrnold** [comment]
> I think that I need more information on what you are trying to accomplish with the if_else example. You provide the following code:

> > resume %>%
> > mutate(BlackFemale = if_else(race == "black" & sex == "female", 1, 0)) %>%
> > group_by(BlackFemale, race, sex) %>%
> > count()

This is a case of the code here not being independent of the QSS text. I added a sentence, but the user probably needs to be reading along in QSS to understand it.

> But it is unclear to me how/why this is any better than simply:

> > resume %>%
> > group_by(race, sex) %>%
> > count()

 It's not. As noted in the text, the group_by table is only used to confirm that the `BlackFemale` column is doing what we think it is doing.

**Comment by jrnold** [comment]
Can you figure out which chunks aren't producing the images?

**Comment by calvinhgarner** [comment]
Code chunks are all producing images fine -- this may have been a problem with something I did, but it appears to be fixed now.
