### ISSUE TITLE
Review and Edit Probability Chapter

### ISSUE THREAD

**Issue by jrnold** [jrnold/qss-tidy#20]
Read and edit the introduction chapter. Fix any problems. Expand, revise, or edit the text for clarity. Ask questions in the comments of this issue or open a new issue if there are major changes that need to be made.

Note: when editing the text, keep to code. We can include comments to explain the code, or adds additional information to QSS, but we can't include so much that we are reproducing QSS.

**Comment by calvinhgarner** [comment]
Very small thing on line 82 -- I think it should say always returns TRUE when k > 365 not when k >= 365 because you could have all unique values at k = 365 (although obviously very unlikely). I made this change.

On line 860 you define the variance of the binomial distribution as \mu right after having defined the population mean as \mu. I replaced with \sigma^2, but let me know if I am missing something.

**Comment by jrnold** [comment]
> Very small thing on line 82 -- I think it should say always returns TRUE when k > 365 not when k >= 365 because you could have all unique values at k = 365 (although obviously very unlikely). I made this change.

You're correct. Nice catch.

> On line 860 you define the variance of the binomial distribution as \mu right after having defined the population mean as \mu. I replaced with \sigma^2, but let me know if I am missing something.

You're not missing anything. It was a typo.
