### ISSUE TITLE
Commits not displaying

### ISSUE THREAD

**Issue by calvinhgarner** [jrnold/qss-tidy#22]
I made two commits on Jan 9 that are not displaying. I did the commit and RStudio and pushed, but nothing displayed on website. Not sure what the problem is... am I forgetting something obvious?

**Comment by jrnold** [comment]
You needed to build the HTML files with [blogdown](https://github.com/rstudio/blogdown). I added some (sparse) instructions to the README.

The way it works is that `blogdown::render_book(...)` renders the HTML pages and puts them into the `docs` folder. The repository is configured with GitHub Pages so that it will serve the files in the `docs` folder; see [this](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch) and [this](https://bookdown.org/yihui/blogdown/github-pages.html).
