### ISSUE TITLE
qss_data_url function

### ISSUE THREAD

**Issue by norawebbwilliams** [jrnold/qss-tidy#9]
I put this into the preliminaries for each chapter. I see that you have it in the common.R file, but I think for now students will  want to see it on the website. I can change that back, if preferred! @jrnold

**Comment by jrnold** [comment]
I think you should put it in the intro only---did I delete that?  I may have when I started reusing it and put it into `common.R`.  If we want to put it in multiple files, then there needs to be a way to define it once and then re-use it. Maybe https://yihui.name/knitr/demo/reference/ or having a chunk that echos the source code without running it (since it will be loaded in `common.R`).

**Comment by norawebbwilliams** [comment]
Yes, it was missing from the intro, but was definitely used there! I'm thinking that it should be explicit in each chapter, so that if students can use each chapter as a standalone as needed, entering the code into their own console.

**Comment by jrnold** [comment]
Try this: http://zevross.com/blog/2014/07/09/making-use-of-external-r-code-in-knitr-and-r-markdown/

**Comment by jrnold** [comment]
That was my bad with the intro. I think I didn't write that function until Chapter 3 or 4 because I got annoyed with copying and pasting really long URLs. And then after I copy and pasted the function a few times, I thought that was redundant. But I didn't add an explanation. There should be section on utility functions.

**Comment by jrnold** [comment]
FYI, I found a cool way to do this in https://yihui.name/knitr/demo/pretty/.
